FROM python:3.9-buster

RUN apt-get update && apt-get install --no-install-recommends -y python3-pip unzip xvfb libxi6 libgconf-2-4 wget

## Installing GOOGLE Chromes
RUN bash -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
    
RUN apt-get update

RUN apt-get install -y google-chrome-stable

## Installing Chrome Driver
RUN wget https://chromedriver.storage.googleapis.com/94.0.4606.41/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip && \
    mv chromedriver /usr/bin/chromedriver && \
    chown root:root /usr/bin/chromedriver && \
    chmod +x /usr/bin/chromedriver

## Installing python modules
RUN pip install selenium pyppeteer asyncio requests

RUN pyppeteer-install