version: '3'

networks:
    my-vuln-app-network:
        external: true

services:
  bdd: 
    build: ./my-vuln-app/bdd
    ports:
      - "3636"
    networks:
      - my-vuln-app-network
    cap_add:
      - SYS_NICE
  server:
    build: ./my-vuln-app/server
    ports:
      - "3000"
    volumes:
      - ./my-vuln-app/server:/server
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      - bdd
    networks:
      - my-vuln-app-network
    restart: on-failure
  client:
    build: ./my-vuln-app/client
    ports:
     - "8080:80"
    volumes:
    - ./my-vuln-app/client:/client
    depends_on:
      - server
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - my-vuln-app-network