FROM python:3.9-buster

RUN apt-get update && apt-get install --no-install-recommends -y python3-pip

RUN pip3 install flask pipenv virtualenv flask_bcrypt flask-restx flask_cors Flask_Migrate pyjwt Flask-Script flask_testing python-dotenv